name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ 1.16, 1.17 ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up golang with version ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test -v ./...
